services:
  web_stack:
    image: nginxdemos/hello:latest
    ports:
      - 8080:80
    deploy:
      # placement:
      #   constraints:
      #     - node.hostname == manager
      #     - node.role == manager   (manager o worker)
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
    networks:
      - mystack-net

networks:
  mystack-net:
    driver: overlay