services:
  flask:
    image: fercdevv/scale-flask:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
    networks:
      - flask-net
  ngnix_service:
    image: fercdevv/scale-nginx:latest
    ports:
      - 8082:80
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 10s
    networks:
      - flask-net
networks:
  flask-net:
    driver: overlay